### ISSUE TITLE
There's no need in porting the plugin anymore

### ISSUE THREAD

**Issue by laughedelic** [HenrikWL/plugin-fish_logo#1]
Hi @HenrikWL. I just wanted to make you aware that the [original fish_logo](https://github.com/laughedelic/fish_logo) plugin is now compatible with oh-my-fish. By the way, it was only needed to move the `fish_logo.fish` file to the `functions/` folder. Why copy the function (and not the completions) to a new repo and not just submit a pull-request?

Anyway, I submitted a pull-request to the package repository to replace the reference to your port with the original repo: https://github.com/oh-my-fish/packages-main/pull/19. Probably your consent will help the maintainers to merge it sooner.

**Comment by HenrikWL** [comment]
I wasn't aware that a fisherman plugin could be made compatible with both fisherman and omf, so I just naively copied the function over into an omf plugin skeleton. As for the completions, I simply forgot about them.

I agree that there's no point in my repo now that yours is omf compatible, so I'll comment on that pull request and hope they expedite it.

**Comment by laughedelic** [comment]
Cool, thanks 👍
